(function(r){"use strict";function p(e){let t;return(window.WFEditor||window.JContentEditor||window.tinyMCE)&&!e.is(":visible")?t=new h(e):window.CodeMirror&&e.next()[0]&&e.next()[0].CodeMirror?t=new b(e):window.ace?t=new k(e):window.CKEDITOR?t=new v(e):t=new C(e),t}function h(e){const t=window.tinymce.editors?.[e.attr("id")]||window.tinymce.EditorManager?.get(e.attr("id"));return{getContent:function(){return t.getContent()},insertContent:function(n){t.execCommand("mceInsertContent",!1,n)},updateContent:function(n,o,i){let s=this.getContent();s=s.substring(0,o)+n+'<span id="tmp-wkid"></span>'+s.substring(i),t.setContent(s),t.selection.select(t.dom.select("#tmp-wkid")[0],!0),t.selection.collapse(!1),t.dom.remove("tmp-wkid",!1),t.focus()},getCursorPosition:function(){const n=t.selection.getBookmark(0),o="[data-mce-type=bookmark]",i=t.dom.select(o);t.selection.select(i[0]),t.selection.collapse();const s="######cursor######",c='<span id="'+s+'"></span>';t.selection.setContent(c);const a=t.getContent({format:"html"}).indexOf(c);return t.dom.remove(s,!1),t.selection.moveToBookmark(n),a}}}function C(e){return{getContent:function(){return e.val()},insertContent:function(t){this.updateContent(t,e.prop("selectionStart"),e.prop("selectionEnd"))},updateContent:function(t,n,o){let i=e.val();const s=n+t.length;i=i.substring(0,n)+t+i.substring(o),e.val(i),e[0].setSelectionRange(s,s),e.focus().trigger("change")},getCursorPosition:function(){return e.prop("selectionStart")}}}function b(e){const t=e.next()[0].CodeMirror;return{getContent:function(){return t.getValue()},insertContent:function(n){t.replaceRange(n,t.getCursor()),t.focus()},updateContent:function(n,o,i){t.replaceRange(n,this.translateOffset(o),this.translateOffset(i)),t.focus()},getCursorPosition:function(){return this.translatePosition(t.getCursor())},translatePosition:function(n){return t.getValue().split(`
`,n.line).join("").length+n.line+n.ch},translateOffset:function(n){const o=t.getValue().substring(0,n).split(`
`);return{line:o.length-1,ch:o[o.length-1].length}}}}function k(e){const t=window.ace.edit(e.parent().attr("id"));return{getContent:function(){return t.getValue()},insertContent:function(n){t.insert(n),t.focus()},updateContent:function(n,o,i){o=this.translateOffset(o),i=this.translateOffset(i);const s=t.getSelectionRange();s.setStart(o.row,o.column),s.setEnd(i.row,i.column),t.getSession().getDocument().replace(s,n),t.focus()},getCursorPosition:function(){return this.translatePosition(t.getSelection().getCursor())},translatePosition:function(n){return this.getContent().split(`
`,n.row).join("").length+n.row+n.column},translateOffset:function(n){const o=this.getContent().substring(0,n).split(`
`);return{row:o.length-1,column:o[o.length-1].length}}}}function v(e){const t=window.CKEDITOR.instances[e.attr("id")];return{getContent:function(){return t.getData()},insertContent:function(n){this.updateContent(n,this.getCursorPosition(),this.getCursorPosition())},updateContent:function(n,o,i){let s=t.getData();s=s.substring(0,o)+n+s.substring(i),t.setData(s)},getCursorPosition:function(){return t.mode==="source"?r(t.textarea.$).prop("selectionStart"):this.getCursorPositionInWYSIWYG()},getCursorPositionInWYSIWYG:function(){const n=t.getSelection().createBookmarks(),i='<span id="'+"######cursor######"+'">&nbsp;</span>',s=window.CKEDITOR.dom.element.createFromHtml(i);s.insertBefore(n[0].startNode);const d=this.getContent().indexOf(i);return s.remove(),t.getSelection().selectBookmarks(n),d}}}const l=function(e){r.extend(this,{tag:"",attrs:{},type:"single",content:""},e)};r.extend(l,{parse:function(e,t){const n=this.regexp(e).exec(t);let o={tag:e},i;return n&&(n[4]?i="self-closing":n[6]?i="closed":i="single",o={tag:n[2],attrs:this.attrs(n[3]),type:i,content:n[5]}),new l(o)},attrs:function(e){const t=/(\w+)\s*=\s*"([^"]*)"(?:\s|$)|(\w+)\s*=\s*'([^']*)'(?:\s|$)|(\w+)\s*=\s*([^\s'"]+)(?:\s|$)|"([^"]*)"(?:\s|$)|(\S+)(?:\s|$)/g,n={};let o;for(e=e.replace(/[\u00a0\u200b]/g," ");o=t.exec(e);)o[1]?n[o[1].toLowerCase()]=o[2]:o[3]?n[o[3].toLowerCase()]=o[4]:o[5]&&(o[6]==="true"||o[6]==="1")?n[o[5].toLowerCase()]=!0:o[5]&&(o[6]==="false"||o[6]==="0")?n[o[5].toLowerCase()]=!1:o[5]?n[o[5].toLowerCase()]=o[6]:o[7]?n[o[7]]=!0:o[8]&&(n[o[8]]=!0);return n},regexp:function(e){return new RegExp("\\[(\\[?)("+e+")(?![\\w-])([^\\]\\/]*(?:\\/(?!\\])[^\\]\\/]*)*?)(?:(\\/)\\]|\\](?:([^\\[]*(?:\\[(?!\\/\\2\\])[^\\[]*)*)(\\[\\/\\2\\]))?)(\\]?)","g")}}),r.extend(l.prototype,{string:function(){let e="["+this.tag;return r.each(this.attrs,function(t,n){typeof n=="boolean"?e+=" "+t+"="+(n?1:0):n!==""&&(e+=" "+t+'="'+n+'"')}),this.type==="single"?e+"]":this.type==="self-closing"?e+" /]":(e+="]",this.content&&(e+=this.content),e+"[/"+this.tag+"]")}});const{Joomla:g}=window;let u,f;window.insertWidgetkitWidget=function(e){const t=p(r(`#${e}`)),n=t.getContent(),o=t.getCursorPosition(),i=/\[widgetkit([^\]]*)\]/gi;let s,c;for(;c=i.exec(n);)if(c.index<=o&&i.lastIndex>o){s=c[0];break}w(d=>{const a=new l({tag:"widgetkit",attrs:d}).string();s?t.updateContent(a,c.index,i.lastIndex):t.insertContent(a)})},r(".widgetkit-widget",".view-module, #module-form, #modules-form").on("click",function(e){e.preventDefault(),w(t=>m(this,t))}).each(function(){m(this)});function w(e){const{iframe:t}=g.getOptions("widgetkit");u=u||r(S(t)).appendTo("body"),u.find(".modal-body").css("height",window.innerHeight*.9),f=y(u),f.show(),window.selectWidget=function(n){e(n),f.hide()}}function S(e){return`<div class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg jviewport-width90" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <iframe src="${e}" style="height: 100%"></iframe>
                </div>
            </div>
        </div>
    </div>`}function y(e){const{bootstrap:t}=window;return t?new t.Modal(e):(r(e).modal().css({width:"90%",marginLeft:"-45%"}),{show(){r(e).modal("show")},hide(){r(e).modal("hide")}})}function m(e,t){const n=e.nextElementSibling,o=t?JSON.stringify(t):n.value,i=E(n.value=o),s=g.getOptions("widgetkit");e.textContent=i.name?s.current.replace("%widget%",i.name):s.select}function E(e){try{return JSON.parse(e)}catch{return{}}}})(jQuery);
